### ISSUE TITLE
NoSuchMethodError in 2.0b8

### ISSUE THREAD

**Issue by derekkinsman** [onformative/YahooWeather#1]
I know Processing 2.0 is still in beta however the current release (2.0b8) is producing the below error. The library still works in 2.0b7.

```
NoSuchMethodError: You may be using a library that's incompatible with this version of Processing.
Exception in thread "Animation Thread" java.lang.NoSuchMethodError: processing.data.XML.<init>(Lprocessing/core/PApplet;Ljava/lang/String;)V
at com.onformative.yahooweather.YahooWeatherThread.setMainXML(YahooWeatherThread.java:64)
at com.onformative.yahooweather.YahooWeatherThread.start(YahooWeatherThread.java:41)
at com.onformative.yahooweather.YahooWeatherThread.<init>(YahooWeatherThread.java:35)
at com.onformative.yahooweather.YahooWeather.<init>(YahooWeather.java:34)
at WeatherSimpleExample.setup(WeatherSimpleExample.java:30)
at processing.core.PApplet.handleDraw(PApplet.java:2241)
at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)
at processing.core.PApplet.run(PApplet.java:2140)
at java.lang.Thread.run(Thread.java:680)
```

**Comment by onformative** [comment]
I just came to check your issue now. I can't reproduce your error, the library is working in b07/b08/b09 for me. Make sure you download and include the right version of the library, it seems to me that you were using the version for processing 1.5. 
Check out the download link on the bottom of this page http://www.onformative.com/lab/google-weather-library-for-processing/ or clone the repository from github here.

**Comment by derekkinsman** [comment]
This was the fix: https://github.com/onformative/YahooWeather/commit/851fffcfaa156c5c48b65d0a93079fb02e612477 — I thought I closed this bug when you pushed this change 3 months ago.
